# Generated by Django 4.2.7 on 2024-03-08 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='Place')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('is_nice_habit', models.BooleanField(blank=True, null=True, verbose_name='Is nice habit?')),
                ('reward', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reward')),
                ('periodicity', models.PositiveIntegerField(verbose_name='Periodicity')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is public')),
                ('time_for_habit', models.PositiveIntegerField(verbose_name='Time for habit')),
                ('associated_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Associated habit')),
            ],
            options={
                'verbose_name': 'Habit',
                'verbose_name_plural': 'Habits',
            },
        ),
    ]
