# Generated by Django 4.2.7 on 2024-03-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='is_nice_habit',
            field=models.BooleanField(default=False, verbose_name='Is nice habit?'),
            preserve_default=False,
        ),
    ]
