# Generated by Django 4.2.7 on 2024-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='duration_time',
            field=models.TimeField(verbose_name='Duration time'),
        ),
    ]
